dcConsData = [
	{name:"o7.png", keywords:["o7"], tags:["오메가스트라이커"]},
	{name:"공부중.gif", keywords:["공부중"], tags:["오메가스트라이커"]},
	{name:"그게무슨소리니.png", keywords:["그게무슨소리니", "무슨소리니"], tags:["오메가스트라이커"]},
	{name:"극혐.png", keywords:["극혐"], tags:["오메가스트라이커"]},
	{name:"너도극혐.png", keywords:["극혐2"], tags:["오메가스트라이커"]},
	{name:"냥슬퍼.png", keywords:["슬퍼"], tags:["오메가스트라이커"]},
	{name:"드렉콘.png", keywords:["드렉콘"], tags:["오메가스트라이커"]},
	{name:"무료입니다.png", keywords:["무료입니다", "무료"], tags:["오메가스트라이커"]},
	{name:"부.png", keywords:["boo", "부"], tags:["오메가스트라이커"]},
	{name:"브이.png", keywords:["브이"], tags:["오메가스트라이커"]},
	{name:"신나.gif", keywords:["신나"], tags:["오메가스트라이커"]},
	{name:"신나.png", keywords:["신나2"], tags:["오메가스트라이커"]},
	{name:"아이미슬퍼.png", keywords:["슬퍼2"], tags:["오메가스트라이커"]},
	{name:"아틀따봉.png", keywords:["따봉"], tags:["오메가스트라이커"]},
	{name:"엄.png", keywords:["엄"], tags:["오메가스트라이커"]},
	{name:"젠묵묵.png", keywords:["젠묵묵"], tags:["오메가스트라이커"]},
	{name:"주노졸려.png", keywords:["졸려"], tags:["오메가스트라이커"]},
	{name:"줄리슬퍼.png", keywords:["슬퍼3"], tags:["오메가스트라이커"]},
	{name:"줄리하트.png", keywords:["사랑해"], tags:["오메가스트라이커"]},
	{name:"타닥타닥.gif", keywords:["타닥타닥"], tags:["오메가스트라이커"]},
	{name:"화이팅.png", keywords:["화이팅"], tags:["오메가스트라이커"]},
	{name:"주노바보.png", keywords:["화이팅2"], tags:["오메가스트라이커"]},
];